name: xuexi
on: 
    workflow_dispatch:
    schedule:
      - cron: '0 3 * * *'

    watch:
        types: [ started ]
jobs:
   build:
       runs-on: windows-latest
       steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.9
            uses: actions/setup-python@v2
            with:
                python-version: 3.9.1
          - name: install pip packages
             run: python -m pip install --upgrade pip
          - name: install selenium
             run: pip install selenium==3.8.1
          - name: run xue
             run: python qiangguo_chrome.py